routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\ValidationController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/loginilhamblog', [ValidationController::class, 'login'])->name('login');
Route::post('actionlogin', [ValidationController::class, 'action'])->name('actionlogin');
Route::get('actionlogout', [ValidationController::class, 'logout'])->name('actionlogout');
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');
Route::resource('blog', BlogController::class)->middleware('auth');
Route::resource('category', CategoryController::class)->middleware('auth');
Route::get('category.all', [CategoryController::class, 'all'])->middleware('auth');

Route::get('/profile', [DashboardController::class, 'profile'])->middleware('auth');

Route::get('/', [FrontEndController::class, 'index']);
Route::get('/{article:slug}', [FrontEndController::class, 'view']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function Articel()
    {
        return $this->hasMany(Articel::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Articel;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.category.index',[
            'title' => 'Category',
            'display' => 'Category',
            'categories' => Category::latest()->limit(7)->get(),
            'all' => Category::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.input',[
            'title' => 'Create New Category',
            'display' => 'Create New Category',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Data = $request->validate([
            'name' => 'required|max:255'
        ]);
        $Data['slug'] = Str::slug($request->name, '-');
        Category::create($Data);
        return redirect('blog');
    }

    /*
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('dashboard.category.show',[
            'title' => "Category $category->name",
            'display'=> "Show $category->name",
            'categories' => $category->articel
        ],compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('dashboard.category.edit',[
            'title' => "Edit nama Category",
            'display' => "Edit name Category"
        ], compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $Data = $request->validate([
            'name' => 'required|max:255'
        ]);

        $Data['slug'] = Str::slug($request->name, '_');

        $category::where('id', $category->id)
                    ->update($Data);
        return redirect('category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }

    public function all(){
        return view('dashboard.category.all',[
            'title' => 'Category',
            'display' => 'Category',
            'categories' => Category::all()
        ]);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Articel;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index',[
            'title' => "dashboard",
            'display' => "Dashboard",
            'tblog' => Articel::count(),
            'tcategory' => Category::count(),
            'blogs' => Articel::limit(10)->get(),
            'categories' => Category::all(),
        ]);
    }

    public function profile(User $profile)
    {
        return view('dashboard.profile.index',[
            'title' => "Profile",
            'display' => 'profile'
        ],compact('profile'));
    }
}

resources/views/dashboard/category/all.blade.php
@extends('dashboard.layouts.main')

@section('content')
<div class="d-flex justify-content-around mb-4">
    <a href="/category" class="btn btn-outline-success rounded-4 col-md-4 col-4"><span class="fal fa-plus"></span> Back</a>
    <a href="{{ route('category.create') }}" class="btn btn-outline-primary rounded-4 col-md-4 col-4"><span class="fal fa-plus"></span> All Category</a>
</div>
<main class="category">
    <table class="table table-striped">
        <tr class="title">
            <th class="no">No</th>
            <th class="name">Category</th>
            <th class="count">Jumlah</th>
            <th class="edit">edit</th>
        </tr>
        @foreach($categories as $category)
            <tr>
                <td class="no">{{ $loop->iteration }}</td>
                <td class="name"><a href="{{ route('category.show',$category->slug) }}">{{ $category->name }}</a>
                </td>
                <td class="count">{{ $category->articel->count() }}</td>
                <td class="edit"><a href="{{ route('category.edit',$category->slug) }}" class="btn btn-sm btn-warning "><span class="fal fa-edit"></span></a></td>
            </tr>
        @endforeach
    </table>
</main>
@endsection

resources/views/dashboard/category/edit.blade.php
@extends('dashboard.layouts.main')

@section('content')
    <form action="{{ route('category.update',$category->slug) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-floating">
            <input type="text" class="form-control" id="name" name="name" value="{{ $category->name }}" placeholder="name">
            <label for="name">name</label>
        </div>

        <button type="submit">UPDATE</button>
    </form>
@endsection 

resources/views/dashboard/category/index.blade.php
@extends('dashboard.layouts.main')

@section('content')
<div class="d-flex justify-content-around mb-4">
    <a href="{{ route('category.create') }}" class="btn btn-outline-success rounded-4 col-md-4 col-lg-4 col-sm-12"><span class="fal fa-plus"></span> Add Category</a>
    <a href="/category.all" class="btn btn-outline-primary rounded-4 col-md-4 col-lg-4 col-sm-12"><span class="fal fa-plus"></span> All Category</a>
</div>
<div class="row justify-content-around">
    <div class="col-lg-5 col-md-5 col-sm-12 mb-3">
        <canvas id="category" style="width: 100%" height="400"></canvas>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
        <main class="category">
            <table class="table table-striped">
                <tr class="title">
                    <th class="no">No</th>
                    <th class="name">Category</th>
                    <th class="count">Jumlah</th>
                    <th class="edit">edit</th>
                </tr>
                @foreach($categories as $category)
                    <tr>
                        <td class="no">{{ $loop->iteration }}</td>
                        <td class="name"><a href="{{ route('category.show',$category->slug) }}">{{ $category->name }}</a>
                        </td>
                        <td class="count">{{ $category->articel->count() }}</td>
                        <td class="edit"><a href="{{ route('category.edit',$category->slug) }}" class="btn btn-sm btn-warning "><span class="fal fa-edit"></span></a></td>
                    </tr>
                @endforeach
            </table>
        </main>
    </div>
</div>
@endsection

resources/views/dashboard/category/input.blade.php
@extends('dashboard.layouts.main')

@section('content')
    <form action="{{ route('category.store') }}" method="POST">
        @csrf
        <div class="form-floating mb-4">
            <input type="text" id="category_id" class="form-control form" name="name" placeholder="name category">
            <label for="category_id">New Category</label>
        </div>
        <button type="submit" class="btn btn-success"><span class="fas fa-plus"></span> Tamba</button>
    </form>
@endsection

resources/views/dashboard/category/show.blade.php
@extends('dashboard.layouts.main')

@section('content')
    <main>
        <table class="table table-blog">
            @foreach ($categories as $category)
                <tr>
                    <td class="col-md-11">
                        <div class="blog-post">
                            <p class="blog-post-title"><b class="h3"><a href="{{ route('blog.show',$category->slug) }}">{{ $category->title }}</a></b></p>
                            <p>
                                <small class="fs-italic"> ---  Category : <a href="{{ $category->category->slug }}">{{ $category->category->name }}. </a> <span class="far fa-calendar"></span> {{ $category->created_at->format('d M Y') }}. ---</small>
                            </p>
                            {!! $category->excerpt !!}
                        </div>
                    </td>
                </tr>
            @endforeach
        </table>
    </main>
@endsection