routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\ValidationController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/loginilhamblog', [ValidationController::class, 'login'])->name('login');
Route::post('actionlogin', [ValidationController::class, 'action'])->name('actionlogin');
Route::get('actionlogout', [ValidationController::class, 'logout'])->name('actionlogout');
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');
Route::resource('blog', BlogController::class)->middleware('auth');
Route::resource('category', CategoryController::class)->middleware('auth');
Route::get('category.all', [CategoryController::class, 'all'])->middleware('auth');

Route::get('/profile', [DashboardController::class, 'profile'])->middleware('auth');

Route::get('/', [FrontEndController::class, 'index']);
Route::get('/{article:slug}', [FrontEndController::class, 'view']);

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Articel;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.blogs.index',[
            'title' => "Blog",
            'display' => "Blog",
            'blogs' => Articel::latest()->paginate(20)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.blogs.input',[
            'title' => 'Create New Blog',
            'display' => 'Create New Blog',
            'categories' => Category::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'title' => 'required|max:255',
            'category_id' => 'required',
            'images' => 'image',
            'body' => 'required'
        ]);

        if($request->file('images')){
            $validateData['images'] = $request->file('images')->store('images');
        }

        $validateData['user_id'] = auth()->user()->id;
        $validateData['slug'] = Str::slug($request->title, '-');
        $validateData['excerpt'] = Str::limit(strip_tags($request->body), 150, '...');
        Articel::create($validateData);
        return redirect('blog');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Articel  $articel
     * @return \Illuminate\Http\Response
     */
    public function show(Articel $blog)
    {
        return view('dashboard.blogs.show',[
            'title' => $blog->title,
            'display' => "Show Articel"
        ]
        , compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Articel  $articel
     * @return \Illuminate\Http\Response
     */
    public function edit(Articel $blog)
    {
        return view('dashboard.blogs.edit',[
            'title' => "Edit | $blog->title",
            'display' => 'Menu Edit',
            'categories' => Category::all()
        ], compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Articel  $articel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Articel $blog)
    {
        $validateData = $request->validate([
            'title' => 'required|max:255',
            'category_id' => 'required',
            'images' => 'image',
            'body' => 'required'
        ]);
        
        if($request->file('images')){
            if($request->oldimage){
                Storage::delete($request->oldimage);
            }
            $validateData['images'] = $request->file('images')->store('images');
        }

        $validateData['user_id'] = auth()->user()->id;
        $validateData['slug'] = Str::slug($request->title, '-');
        $validateData['excerpt'] = Str::limit(strip_tags($request->body), 100 ,'...');

        $blog::where('id', $blog->id)
                ->update($validateData);
        return redirect('blog')->with('edit', 'blog ber');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Articel  $articel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Articel $blog)
    {
        if ($blog->images) {
            Storage::delete($blog->images);
        }
        $blog->delete();
        return redirect('blog');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Articel;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index',[
            'title' => "dashboard",
            'display' => "Dashboard",
            'tblog' => Articel::count(),
            'tcategory' => Category::count(),
            'blogs' => Articel::limit(10)->get(),
            'categories' => Category::all(),
        ]);
    }

    public function profile(User $profile)
    {
        return view('dashboard.profile.index',[
            'title' => "Profile",
            'display' => 'profile'
        ],compact('profile'));
    }
}

resources/views/dashboard/blogs/edit.blade.php
@extends('dashboard.layouts.main')

@section('content')
<main>
    <form action="{{ route('blog.update',$blog->slug) }}" method="post" class="mt-3" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="form-floating form">
        <input type="text" name="title" class="title form-control form  @error('title') is-invalid @enderror" placeholder="Title" value="{{ $blog->title }}">
        <label for="title">Title</label>
        @error('title')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="mb-3">
        <input type="hidden" name="oldimage" value="{{ $blog->images }}">
        @if ($blog->images)
            <img src="{{ asset('storage/' . $blog->images) }}" class="image-preview img-fluid col-sm-5 d-block">
        @else
            <img class="image-preview" alt="">
        @endif

        <input type="file" class="form-control forms  @error('image') is-invalid @enderror" id="images" onchange="ImagePreview()" name="images">
        @error('image')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>

    <div class="form-floating form">
        <select name="category_id" class="form form-control form-select mb-3" id="">
            @foreach ($categories as $category)
            @if (old('category_id', $blog->category_id) == $category->id)
                <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
            @else
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endif
            @endforeach
        </select>
        <label for="Category_id">Category</label>
    </div>

    <div class="mt-5 input-body">
        <label for="body" class="form-label h4 d-flex justify-content-center mb-3  @error('body') is-invalid @enderror">Body</label>
        <input type="hidden" id="body" name="body" required value="{{ $blog->body }}">
        <trix-editor input="body"></trix-editor>
        @error('body')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <button type="submit" class="btn btn-success">Publish</button>
    </form>
</main>
@endsection

resources/views/dashboard/blogs/index.blade.php
@extends('dashboard.layouts.main')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center p-2">
<h1 class="h2">Statistic</h1>
<button type="button" class="btn btn-sm btn-outline-secondary rounded-2 dropdown-toggle" data-bs-toggle="dropdown">This Week</button>
    <ul class="dropdown-menu">
        <li><a href="" class="dropdown-item">This Month</a></li>
        <li><a href="" class="dropdown-item">This Years</a></li>
    </ul>
</div>
<div class="canvas">
<canvas id="myChart" style="width: 100%" height="460vh"></canvas>
</div>
{{-- <div class="row">
    <div class="col-md-8">
        <div class="top blog-top text-center mb-5">
            <div class="blog">
                <div class="info">
                    <a href="/blog">
                    <h3><span class="fas fa-list-ul"></span> All Blog's</h3>
                    <hr>
                    <h1>12</h1>
                    </a>
                </div>
            </div>
            <div class="blog">
                <div class="info">
                    <a href="/blog">
                    <h3><span class="fas fa-list-ul"></span> Blog's in Week</h3>
                    <hr>
                    <h1>12</h1>
                    </a>
                </div>
            </div>
            <div class="draf">
                <div class="info">
                    <h3><span class="far fa-bookmark"></span> All Draf</h3>
                    <hr>
                    <h1>12</h1>
                </div>
            </div>
            <div class="draf">
                <div class="info">
                    <h3><span class="far fa-bookmark"></span> Draf in Week</h3>
                    <hr>
                    <h1>12</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        
    </div>
</div> --}}
<div class="row">
    <section>
        <h1 class="h1 text-center">--- All Blog's ---</h1>
        <div class="row">
            <div class="col-md-10 col-10">
                <a href="{{ route('blog.create') }}" class="btn btn-success col-md-3 col-6 rounded-4"><span class="fas fa-plus"></span> Tambah</a>
            </div>

            <div class="d-flex justify-content-end col-md-2 col-2">
                <button class="btn" type="button" data-bs-toggle="dropdown"><span class="fas fa-sort"></span></button>
                <ul class="dropdown-menu">
                    <li><a href="" class="dropdown-item"><span class="fas fa-sort-alpha-up"></span> Urutkan Berdasarkan Abjad</a></li>
                    <li><a href="" class="dropdown-item"><span class="fas fa-sort-amount-up"></span> Urutkan Berdasarkan yang terbaru</a></li>
                </ul>
            </div>
        </div>

        <table class="table table-blog">
            @foreach ($blogs as $blog)
            <tr>
                <td class="col-md-11">
                    <div class="blog-post">
                        <p class="blog-post-title"><b class="h3"><a href="{{ route('blog.show',$blog->slug) }}">{{ $blog->title }}</a></b></p>
                        <p>
                            <small>
                                <cite>Category : <a href="{{ route('category.show',$blog->category->slug) }}">{{ $blog->category->name }}.</a> <span class="far fa-calendar"></span>  {{ $blog->created_at->format('d M Y') }}.</cite>
                            </small>
                        </p>
                        <div>
                            {!! $blog->excerpt !!}
                        </div>
                    </div>
                </td>
            <td>
                <div class="dropstart">
                    <form action="{{ route('blog.destroy',$blog->slug) }}" method="post">
                        @csrf
                        @method('DELETE')
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="fas fa-ellipsis-h"></span>
                    </button>
                    <div class="back"></div>
                    <ul class="dropdown-menu drop">
                      <li><a class="dropdown-item" href="{{ route('blog.edit',$blog->slug) }}"><span class="fas fa-file-pen"></span> Edit</a></li>
                      <li><button type="submit" class="dropdown-item" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')"><span class="fas fa-trash-can " ></span> Delete</button></li>
                    </ul>
                    </form>
                  </div>
            </td>
        </tr>
        @endforeach
        </table>
    </section>
</div>
@endsection

resources/views/dashboard/blogs/input.blade.php
@extends('dashboard.layouts.main')

@section('content')
    <form action="{{ route('blog.store') }}" method="post" class="mt-3" enctype="multipart/form-data">
        @csrf
        <div class="d-flex justify-content-end mb-3">
        <button class="btn" type="button" data-bs-toggle="dropdown">
            <span class="fas fa-ellipsis-h"></span>
        </button>
        
        <ul class="dropdown-menu">
            <li><a href="/back" class="dropdown-item"><span class="fas fa-left-long"></span> Kembali</a></li>
            <li><button type="submit" class="dropdown-item"><span class="fas fa-globe-asia"></span> Publish</button></li>
        </ul>
        </div>

        <div class="form-floating">
            <input type="text" class="title form-control form @error('title') is-invalid @enderror" placeholder="Title" name="title" value="{{ old('title') }}">
            @error('title')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
            <label for="title">Title</label>
        </div>

        <div class="image">
            <img class="image-preview d-flex justify-content-center img-fluid">
            <input type="file" class="form-control form  @error('image') is-invalid @enderror" id="images" name="images" onchange="ImagePreview()" placeholder="img" value="{{ old('image') }}">
            @error('image')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>

        <div class="form-floating">
            <select name="category_id" class="form form-control form-select">
                @foreach ($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
            <label for="category_id">Category</label>
        </div>

        <div class="mt-5 input-body">
            <label for="body" class="form-label h4 d-flex justify-content-center mb-3  @error('body') is-invalid @enderror">Body</label>
            @error('body')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
            <input type="hidden" id="body" name="body" required value="{{ old('body') }}">
            <trix-editor input="body"></trix-editor>
        </div>
    </form>
@endsection

resources/views/dashboard/blogs/show.blade.php
@extends('dashboard.layouts.main')

@section('content')
    <main class="show">
        <form action="{{ route('blog.destroy',$blog->slug) }}" class="mb-3" method="POST">
            @method('DELETE')
            @csrf
            <a href="/blog" class="btn btn-primary"><span class="fas fa-left-long"></span><span>Kembali</span></a>
            <a href="{{ route('blog.edit',$blog->slug) }}" class="btn btn-warning"><span class="fas fa-edit"></span> Edit</a>
            <button class="btn btn-danger" onclick="return confirm('apakah anda ingin menghapus blog ini?')"><span class="fas fa-trash-can"></span> Delete</button>
        </form>
        <div class="preview">
        <h1 class="justify-content-center">{{ $blog->title }}</h1>
        <div class="d-flex justify-content-center">
        @if ($blog->images)
        <img src="{{ asset('storage/' . $blog->images) }}">
        @else
        <img src="/image/bg-showcase-2.jpg" class="mb-3">
        @endif
        </div>
        <p>{!! $blog->body !!}</p>
        </div>
    </main>
@endsection